name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"
[commands]
predev = "node scripts/generate-local-schema.js && npm exec prisma generate -- --schema=prisma/schema.local.prisma"
dev = "npm exec prisma db push -- --skip-generate --schema=prisma/schema.local.prisma && npm exec react-router dev"
